<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ClassRoomsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('class_rooms')->insert([
            [
                'id' => '15DTH01',
                'faculty_id' => 'DTH',
                'uid_secretary' => 47,
                'uid_deputysecre1' => 48,
                'uid_deputysecre2' => 49,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '15DTH02',
                'faculty_id' => 'DTH',
                'uid_secretary' => 40,
                'uid_deputysecre1' => 41,
                'uid_deputysecre2' => 42,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '15DTH03',
                'faculty_id' => 'DTH',
                'uid_secretary' => 8,
                'uid_deputysecre1' => 9,
                'uid_deputysecre2' => 10,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '15DTH04',
                'faculty_id' => 'DTH',
                'uid_secretary' => 44,
                'uid_deputysecre1' => 45,
                'uid_deputysecre2' => 46,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '15DTH05',
                'faculty_id' => 'DTH',
                'uid_secretary' => 9,
                'uid_deputysecre1' => 10,
                'uid_deputysecre2' => 11,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '15DTH06',
                'faculty_id' => 'DTH',
                'uid_secretary' => 10,
                'uid_deputysecre1' => 11,
                'uid_deputysecre2' => 12,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '15DTH07',
                'faculty_id' => 'DTH',
                'uid_secretary' => 11,
                'uid_deputysecre1' => 12,
                'uid_deputysecre2' => 13,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '15DTH08',
                'faculty_id' => 'DTH',
                'uid_secretary' => 12,
                'uid_deputysecre1' => 13,
                'uid_deputysecre2' => 14,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '15DTH09',
                'faculty_id' => 'DTH',
                'uid_secretary' => 13,
                'uid_deputysecre1' => 14,
                'uid_deputysecre2' => 15,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '15DTH10',
                'faculty_id' => 'DTH',
                'uid_secretary' => 14,
                'uid_deputysecre1' => 15,
                'uid_deputysecre2' => 16,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '15DTH11',
                'faculty_id' => 'DTH',
                'uid_secretary' => 15,
                'uid_deputysecre1' => 16,
                'uid_deputysecre2' => 17,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '15DTH12',
                'faculty_id' => 'DTH',
                'uid_secretary' => 16,
                'uid_deputysecre1' => 17,
                'uid_deputysecre2' => 18,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '15DTH13',
                'faculty_id' => 'DTH',
                'uid_secretary' => 17,
                'uid_deputysecre1' => 18,
                'uid_deputysecre2' => 19,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '15DTH14',
                'faculty_id' => 'DTH',
                'uid_secretary' => 18,
                'uid_deputysecre1' => 19,
                'uid_deputysecre2' => 20,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '15DTH15',
                'faculty_id' => 'DTH',
                'uid_secretary' => 19,
                'uid_deputysecre1' => 20,
                'uid_deputysecre2' => 21,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '15DTH16',
                'faculty_id' => 'DTH',
                'uid_secretary' => 20,
                'uid_deputysecre1' => 21,
                'uid_deputysecre2' => 22,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            //=======================================================
            [
                'id' => '16DTHA1',
                'faculty_id' => 'DTH',
                'uid_secretary' => 21,
                'uid_deputysecre1' => 22,
                'uid_deputysecre2' => 23,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DTHA2',
                'faculty_id' => 'DTH',
                'uid_secretary' => 22,
                'uid_deputysecre1' => 23,
                'uid_deputysecre2' => 24,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DTHA3',
                'faculty_id' => 'DTH',
                'uid_secretary' => 23,
                'uid_deputysecre1' => 24,
                'uid_deputysecre2' => 25,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DTHA4',
                'faculty_id' => 'DTH',
                'uid_secretary' => 24,
                'uid_deputysecre1' => 25,
                'uid_deputysecre2' => 26,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DTHA5',
                'faculty_id' => 'DTH',
                'uid_secretary' => 25,
                'uid_deputysecre1' => 26,
                'uid_deputysecre2' => 27,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DTHA6',
                'faculty_id' => 'DTH',
                'uid_secretary' => 26,
                'uid_deputysecre1' => 27,
                'uid_deputysecre2' => 28,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DTHB1',
                'faculty_id' => 'DTH',
                'uid_secretary' => 27,
                'uid_deputysecre1' => 28,
                'uid_deputysecre2' => 29,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DTHB2',
                'faculty_id' => 'DTH',
                'uid_secretary' => 28,
                'uid_deputysecre1' => 29,
                'uid_deputysecre2' => 30,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DTHB3',
                'faculty_id' => 'DTH',
                'uid_secretary' => 29,
                'uid_deputysecre1' => 30,
                'uid_deputysecre2' => 31,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DTHB4',
                'faculty_id' => 'DTH',
                'uid_secretary' => 30,
                'uid_deputysecre1' => 31,
                'uid_deputysecre2' => 32,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DTHB5',
                'faculty_id' => 'DTH',
                'uid_secretary' => 31,
                'uid_deputysecre1' => 32,
                'uid_deputysecre2' => 33,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DTHB6',
                'faculty_id' => 'DTH',
                'uid_secretary' => 32,
                'uid_deputysecre1' => 33,
                'uid_deputysecre2' => 34,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            //=======================================================
            [
                'id' => '16DDUA1',
                'faculty_id' => 'DDU',
                'uid_secretary' => 35,
                'uid_deputysecre1' => 36,
                'uid_deputysecre2' => 37,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DDUA2',
                'faculty_id' => 'DDU',
                'uid_secretary' => 36,
                'uid_deputysecre1' => 37,
                'uid_deputysecre2' => 38,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DDUA3',
                'faculty_id' => 'DDU',
                'uid_secretary' => 37,
                'uid_deputysecre1' => 38,
                'uid_deputysecre2' => 39,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DDUA4',
                'faculty_id' => 'DDU',
                'uid_secretary' => 38,
                'uid_deputysecre1' => 39,
                'uid_deputysecre2' => 40,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DDUA5',
                'faculty_id' => 'DDU',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 7,
                'uid_deputysecre2' => 9,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DDUA6',
                'faculty_id' => 'DDU',
                'uid_secretary' => 6,
                'uid_deputysecre1' => 8,
                'uid_deputysecre2' => 10,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DDUB1',
                'faculty_id' => 'DDU',
                'uid_secretary' => 11,
                'uid_deputysecre1' => 13,
                'uid_deputysecre2' => 15,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DDUB2',
                'faculty_id' => 'DDU',
                'uid_secretary' => 12,
                'uid_deputysecre1' => 14,
                'uid_deputysecre2' => 16,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DDUB3',
                'faculty_id' => 'DDU',
                'uid_secretary' => 17,
                'uid_deputysecre1' => 19,
                'uid_deputysecre2' => 21,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DDUB4',
                'faculty_id' => 'DDU',
                'uid_secretary' => 18,
                'uid_deputysecre1' => 20,
                'uid_deputysecre2' => 22,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DDUB5',
                'faculty_id' => 'DDU',
                'uid_secretary' => 23,
                'uid_deputysecre1' => 25,
                'uid_deputysecre2' => 27,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DDUB6',
                'faculty_id' => 'DDU',
                'uid_secretary' => 24,
                'uid_deputysecre1' => 26,
                'uid_deputysecre2' => 28,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            //=======================================================
            [
                'id' => '16DQTA1',
                'faculty_id' => 'DQT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DQTA2',
                'faculty_id' => 'DQT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DQTA3',
                'faculty_id' => 'DQT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DQTA4',
                'faculty_id' => 'DQT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DQTA5',
                'faculty_id' => 'DQT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DQTA6',
                'faculty_id' => 'DQT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DQTB1',
                'faculty_id' => 'DQT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DQTB2',
                'faculty_id' => 'DQT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DQTB3',
                'faculty_id' => 'DQT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DQTB4',
                'faculty_id' => 'DQT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DQTB5',
                'faculty_id' => 'DQT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DQTB6',
                'faculty_id' => 'DQT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            //=======================================================
            [
                'id' => '16DKTA1',
                'faculty_id' => 'DKT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DKTA2',
                'faculty_id' => 'DKT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DKTA3',
                'faculty_id' => 'DKT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DKTA4',
                'faculty_id' => 'DKT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DKTA5',
                'faculty_id' => 'DKT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DKTA6',
                'faculty_id' => 'DKT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DKTB1',
                'faculty_id' => 'DKT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DKTB2',
                'faculty_id' => 'DKT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DKTB3',
                'faculty_id' => 'DKT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DKTB4',
                'faculty_id' => 'DKT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DKTB5',
                'faculty_id' => 'DKT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => '16DKTB6',
                'faculty_id' => 'DKT',
                'uid_secretary' => 5,
                'uid_deputysecre1' => 6,
                'uid_deputysecre2' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
        ]);
    }
}
